FAIL
Kernel panic in run: PANIC at ../../threads/synch.c:223 in lock_release(): assertion `lock_held_by_current_thread (lock)' failed.
Call stack: 0x80042132cf 0x8004209e32 0x8004218314 0x800420724e
Translation of call stack:
0x00000080042132cf: debug_panic (lib/kernel/debug.c:32)
0x0000008004209e32: lock_release (threads/synch.c:225)
0x0000008004218314: medium_thread_func (tests/threads/priority-donate-nest.c:79)
0x000000800420724e: kernel_thread (threads/thread.c:408)
